site_name: NEXTERA 

nav:
  - CONTROL DE CANVIS: cdecanvis.md
  - GUIA DEL PROGRAMADOR: gprogramador.md
  - WIKI: wiki.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'pink'
  features:
    - navigation.tabs  


custom_dir: 'docs/styles'
extra_css:
  - styles/extra.css
